# craftable spawn eggs by Codingtypo
# config file by Geert225
# configration for commands
enabled_commands:
  toggle: true
  givegui: true
baseitem: 'diamond'
# Configuration for spawn eggs
enabled_spawn_eggs:
  bat:
    enabled: true
  cat:
    enabled: true
  chicken:
    enabled: true
  cod:
    enabled: true
  cow:
    enabled: true
  donkey:
    enabled: true
  fox:
    enabled: true
  horse:
    enabled: true
  mooshroom:
    enabled: true
  mule:
    enabled: true
  ocelot:
    enabled: true
  panda:
    enabled: true
  parrot:
    enabled: true
  pig:
    enabled: true
  rabbit:
    enabled: true
  salmon:
    enabled: true
  sheep:
    enabled: true
  skeleton_horse:
    enabled: true
  snow_man:
    enabled: true
  squid:
    enabled: true
  strider:
    enabled: true
  tropical_fish:
    enabled: true
  turtle:
    enabled: true
  villager:
    enabled: true
  blaze:
    enabled: true
  creeper:
    enabled: true
  drowned:
    enabled: true
  elder_guardian:
    enabled: true
  ender_dragon:
    enabled: true
  endermite:
    enabled: true
  evoker:
    enabled: true
  ghast:
    enabled: true
  guardian:
    enabled: true
  hoglin:
    enabled: true
  husk:
    enabled: true
  illusioner:
    enabled: true
  magma_cube:
    enabled: true
  phantom:
    enabled: true
  piglin:
    enabled: true
  piglin_brute:
    enabled: true
  pillager:
    enabled: true
  ravager:
    enabled: true
  shulker:
    enabled: true
  silverfish:
    enabled: true
  skeleton:
    enabled: true
  slime:
    enabled: true
  stray:
    enabled: true 
  vex:
    enabled: true
  vindicator:
    enabled: true
  witch:
    enabled: true
  wither:
    enabled: true
  wither_skeleton:
    enabled: true
  zoglin:
    enabled: true
  zombie:
    enabled: true
  zombie_villager:
    enabled: true
  bee:
    enabled: true
  cave_spider:
    enabled: true
  dolphin:
    enabled: true
  enderman:
    enabled: true
  llama:
    enabled: true
  polar_bear:
    enabled: true
  pufferfish:
    enabled: true
  spider:
    enabled: true
  wolf:
    enabled: true
  zombified_piglin:
    enabled: true
